title: DataHerb
description: A static, forkable data catalog and explorer for your organization's open data. No backend.
author: DataHerb
url: https://dataherb.github.io
baseurl: ''
lang: en
logo: /assets/favicon/ms-icon-310x310.png
github_username: DataHerb

explorer_url: https://dataherb.github.io/dataherb-explorer/
explorer_repo: https://github.com/DataHerb/dataherb-explorer

google_analytics: UA-158106645-1

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    default_lang: plaintext
    css_class: highlight
excerpt_separator: "\n\n"
timezone: America/New_York
permalink: /:categories/:title/

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor']

collections:
  flora:
    output: true
    permalink: /:collection/:path/
  articles:
    output: true

defaults:
  - scope: { path: "", type: posts }
    values: { layout: post, comments: true }
  - scope: { path: "", type: flora }
    values: { layout: dataherb }
  - scope: { path: "", type: articles }
    values: { layout: articles, comments: true }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
